# 鏁版嵁婧愰厤缃?spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 涓诲簱鏁版嵁婧?            master:
                url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 123456
            # 浠庡簱鏁版嵁婧?            slave:
                # 浠庢暟鎹簮寮€鍏筹紝榛樿鍏抽棴
                enabled: false
                url:
                username:
                password:
            # 鍒濆杩炴帴鏁?            initialSize: 5
            # 鏈€灏忚繛鎺ユ睜鏁伴噺
            minIdle: 10
            # 鏈€澶ц繛鎺ユ睜鏁伴噺
            maxActive: 20
            # 鑾峰彇杩炴帴绛夊緟瓒呮椂鏃堕棿
            maxWait: 60000
            # 杩炴帴瓒呮椂鏃堕棿
            connectTimeout: 30000
            # 缃戠粶瓒呮椂鏃堕棿
            socketTimeout: 60000
            # 妫€娴嬬┖闂茶繛鎺ョ殑鏃堕棿闂撮殧锛屽崟浣嶆绉?            timeBetweenEvictionRunsMillis: 60000
            # 杩炴帴鍦ㄦ睜涓殑鏈€灏忕敓瀛樻椂闂达紝鍗曚綅姣
            minEvictableIdleTimeMillis: 300000
            # 杩炴帴鍦ㄦ睜涓殑鏈€澶х敓瀛樻椂闂达紝鍗曚綅姣
            maxEvictableIdleTimeMillis: 900000
            # 妫€娴嬭繛鎺ユ槸鍚︽湁鏁?            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 鍏佽璁块棶鐨勭櫧鍚嶅崟锛岀暀绌鸿〃绀哄厑璁告墍鏈夊湴鍧€
                allow:
                url-pattern: /druid/*
                # 鎺у埗鍙扮櫥褰曡处鍙峰瘑鐮?                login-username: qinghe
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 鎱?SQL 璁板綍
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
